export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Hero } from './Hero/Hero'
export { default as TopMovies } from './TopMovies/TopMovies'
export { default as LikeButton } from './LikeButton/LikeButton'
export { default as Modal } from './Modal/Modal'
export { default as MovieCard } from './MovieCard/MovieCard'
export { default as SearchFilters } from './SearchFilters/SearchFilters'
